### ISSUE TITLE
PyTenable Not Retrieving WAS Results

### ISSUE THREAD

**Issue by pdreeves** [tenable/pyTenable#289] opened 2021-03-25 22:00 UTC
**Describe the bug**
After March 1st, PyTenable is unable to retrieve WAS results from Tenable.io.

**To Reproduce**
1. Create Tenable.io object `tio = TenableIO(access_key="123", secret_key="123")`
2. List scans `tio.scans.list(last_modified = since27days)`
3. Oberve that WAS results are not present, but network vuln and asset discovery scans are.

**Expected behavior**
WAS results be listed in the response to the tio.scans.list call.

**System Information (please complete the following information):**
 - PyTenable version 1.2.8

**Comment by d0n601** [comment] 2021-05-21 04:01
Tenable changed their API for WAS scans some months ago. This is also the reason that once you cut over to the new user interface, the old UI becomes archive only (the old UI hit the old API endpoints).

To get WAS scan results the endpoint is now `https://cloud.tenable.com/was/v2/scans`, see docs [here](https://developer.tenable.com/reference#was-v2-scans-details).

Basically, I don't think PyTenable is updated to support interacting with WAS scans (launching, configuring, retrieving, etc).

**Comment by levwais** [comment] 2021-06-23 17:16
@pdreeves  - is the suggestion by @d0n601 fix your issue? can I close this issue?
if not, can you please add more details if this still happens?
thanks.

**Comment by pdreeves** [comment] 2021-06-23 21:18
@levwais Yes, that worked and we updated our Lambda function to use the new API.  If you want to close this issue that's fine.  I just wanted to report that PyTenable was unable to retrieve WAS results.  Thank you!

**Comment by SteveMcGrath** [comment] 2021-09-22 15:32
pyTenable was written to interface to the old v1 endpoints, which have been depricated.  It's on our roadmap to support v2

**Comment by SteveMcGrath** [comment] 2021-09-22 15:33
Duplicate of #310

**Closed by SteveMcGrath** 2021-09-22 15:33 UTC
Labels: enhancement, backlog
