### ISSUE TITLE
TenableSC - hosts endpoint

### ISSUE THREAD

**Issue by 6illess** [tenable/pyTenable#631] opened 2022-10-18 12:46 UTC
**Is your feature request related to a problem? Please describe.**
Tenable recently introduced a "/hosts/download::POST" endpoint for exporting Host Assets.
This feature is not (yet) available in pyTenable.
https://docs.tenable.com/tenablesc/api/Changelog.htm

**Describe the solution you'd like**
Build a class in pyTenable which uses this new endpoint.
Revise the current functions in other classes to check if we can directly export assetID's (although I'm not sure Tenable supports this, I don't think they introduced this yet)

**Describe alternatives you've considered**
At the moment we calculate our own ID (md5 hash) based on the parameters within "hostUniqueness" which is exported via the endpoint analysis/vulns/vulndetails. This ensures we copy the uniqueness logic from Tenable.
Since Tenable now introduced this in their API, it makes more sense to copy the same value rather than calculating it ourselves.

**Additional context**
/

**Comment by SteveMcGrath** [comment] 2022-10-25 13:30
These APIs are still flagged as BETA and may yet change.

**Comment by SteveMcGrath** [comment] 2022-12-05 20:10
Duplicate of #614

**Closed by SteveMcGrath** 2022-12-05 20:10 UTC
Labels: enhancement, backlog, Tenable.sc
