### ISSUE TITLE
Target Group Filter not working - type mismatch

### ISSUE THREAD

**Issue by jwoodsj-net** [tenable/pyTenable#97] opened 2019-03-21 15:56 UTC
Cannot use target_group as a filter for workbench queries in io. Seems that the type checker is requiring a string value, but the list of possible values are int.

Response to query when filter value given as integer:

vul = tio.workbenches.vulns(('target_group','eq',1084))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bibble/.local/lib/python3.6/site-packages/tenable/io/workbenches.py", line 471, in vulns
    self._api.filters.workbench_vuln_filters())
  File "/home/bibble/.local/lib/python3.6/site-packages/tenable/io/workbenches.py", line 39, in _workbench_query
    query = self._parse_filters(filters, filterdefs)
  File "/home/bibble/.local/lib/python3.6/site-packages/tenable/io/base.py", line 36, in _parse_filters
    pattern=filterset[f[0]]['pattern'])
  File "/home/bibble/.local/lib/python3.6/site-packages/tenable/base.py", line 208, in _check
    expected_type.__name__ if hasattr(expected_type, '__name__') else expected_type
TypeError: filter_value is of type int.  Expected str.

Response to query when filter value given as string. Note that the requested value is in the accepted values list:

vul = tio.workbenches.vulns(('target_group','eq','1084'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bibble/.local/lib/python3.6/site-packages/tenable/io/workbenches.py", line 471, in vulns
    self._api.filters.workbench_vuln_filters())
  File "/home/bibble/.local/lib/python3.6/site-packages/tenable/io/workbenches.py", line 39, in _workbench_query
    query = self._parse_filters(filters, filterdefs)
  File "/home/bibble/.local/lib/python3.6/site-packages/tenable/io/base.py", line 36, in _parse_filters
    pattern=filterset[f[0]]['pattern'])
  File "/home/bibble/.local/lib/python3.6/site-packages/tenable/base.py", line 225, in _check
    name, obj, ','.join([str(i) for i in choices])
tenable.errors.UnexpectedValueError: filter_value has value of 1084.  Expected one of 1084,1161,1085,1086,1087,1088,1097,1089,1090,1162,1093,1094,1095,1163,1164,1096,1098,1165,1099,1100,1166,1167,1052,1051,1050,1091,1168,1092,1169,1170,1053,1083,1171,1047,1049,1045,1043,1048,1046,1044,1040

**Comment by SteveMcGrath** [comment] 2019-03-21 17:19
Please verify that this works as intended with the master branch.

**Comment by SteveMcGrath** [comment] 2019-03-27 20:06
0.3.14 released with this fix in place.  Closing the issue.  If the problem still exists, please re-open

**Closed by SteveMcGrath** 2019-03-27 20:06 UTC
Labels: bug
