### ISSUE TITLE
Permissions between API and Web GUI seem different

### ISSUE THREAD

**Issue by maaren** [tenable/pyTenable#163] opened 2019-11-04 13:31 UTC
**Describe the bug**
Through the Tenable.IO web gui a Scan Operator can create scan using an existing policy, but when I use tio.scans.create() I get "You are not authorized to perform this request".

**To Reproduce**
1. Login as Scan Operator
2. Click on New Scan
3. Configure the scan
4. Select Launch
5. Scan works
6. Using the API, eg:
 scan = tio.scans.create(name="myscan",policy="mypolicy") (I tried a number of options, I get):
GET https://cloud.tenable.com/editor/policy/templates >> b50cbe12ff87c5d9609dfe40777fa8f3:403 {"error":"You are not authorized to perform this request"}
Traceback (most recent call last):
  File "./mytioscan", line 41, in <module>
    main()
  File "./mytioscan", line 26, in main
    scan = tio.scans.create(name="myscan", policy="mypolicy")
  File "/usr/lib/python3.7/site-packages/tenable/io/scans.py", line 369, in create
    scan = self._create_scan_document(kw)
  File "/usr/lib/python3.7/site-packages/tenable/io/scans.py", line 99, in _create_scan_document
    templates = self._api.policies.templates()
  File "/usr/lib/python3.7/site-packages/tenable/io/policies.py", line 35, in templates
    for item in self._api.editor.template_list('policy'):
  File "/usr/lib/python3.7/site-packages/tenable/io/editor.py", line 236, in template_list
    self._check('etype', etype, str, choices=['scan', 'policy'])
  File "/usr/lib/python3.7/site-packages/tenable/base.py", line 475, in get
    return self._request('GET', path, **kwargs)
  File "/usr/lib/python3.7/site-packages/tenable/base.py", line 446, in _request
    raise self._error_codes[status](resp)
tenable.errors.PermissionError: b50cbe12ff87c5d9609dfe40777fa8f3:403 {"error":"You are not authorized to perform this request"}

**Expected behavior**
I would expect that a Scan Operator can create a scan using the API.

**Comment by maaren** [comment] 2019-11-05 12:51
Hope this helps. I used the following code and ran it as Administrator and Scan Operator:
```
    folder_id = get_folder_id(tio, folder)
    policy_id = get_policy_id(tio, scan_policy)
    scanner_uuid = get_scanner_uuid(tio, 'lpsec002-nessus-scanner')

    params = { 'folder_id':folder_id, 'targets':targets, 'name':scan_name, 'policy':policy_id, 'scanner':scanner_uuid }
    
    scan = tio.scans.create(**params)
         
    tio.scans.launch(scan['id'])
```
Output (I have shortened all the uuid's):
```
$ ./mytioscan
Using Scan Operator  priviliges
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cloud.tenable.com:443
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /folders HTTP/1.1" 200 None
DEBUG:tenable.io.TenableIO:Request-UUID 79 for https://cloud.tenable.com/folders
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /policies HTTP/1.1" 200 568
DEBUG:tenable.io.TenableIO:Request-UUID 50 for https://cloud.tenable.com/policies
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /scanners HTTP/1.1" 403 None
DEBUG:tenable.io.TenableIO:Request-UUID 17 for https://cloud.tenable.com/scanners
ERROR:tenable.errors.PermissionError:GET https://cloud.tenable.com/scanners >> 17:403 {"statusCode":403,"error":"Forbidden","message":"Insufficient scope"}
Traceback (most recent call last):
  File "./mytioscan", line 119, in <module>
    main()
  File "./mytioscan", line 90, in main
    scanner_uuid = get_scanner_uuid(tio, 'nessus-scanner')
  File "./mytioscan", line 27, in get_scanner_uuid
    for scanner in tio.scanners.list():
  File "/usr/lib/python3.7/site-packages/tenable/io/scanners.py", line 268, in list
    return self._api.get('scanners').json()['scanners']
  File "/usr/lib/python3.7/site-packages/tenable/base.py", line 475, in get
    return self._request('GET', path, **kwargs)
  File "/usr/lib/python3.7/site-packages/tenable/base.py", line 446, in _request
    raise self._error_codes[status](resp)
tenable.errors.PermissionError: 17:403 {"statusCode":403,"error":"Forbidden","message":"Insufficient scope"}
```
and as Administrator it works:
```
 ./mytioscan
Using Administrator priviliges
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cloud.tenable.com:443
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /folders HTTP/1.1" 200 None
DEBUG:tenable.io.TenableIO:Request-UUID c8 for https://cloud.tenable.com/folders
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /policies HTTP/1.1" 200 614
DEBUG:tenable.io.TenableIO:Request-UUID a8 for https://cloud.tenable.com/policies
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /scanners HTTP/1.1" 200 None
DEBUG:tenable.io.TenableIO:Request-UUID 71 for https://cloud.tenable.com/scanners
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /editor/policy/templates HTTP/1.1" 200 2374
DEBUG:tenable.io.TenableIO:Request-UUID 9b for https://cloud.tenable.com/editor/policy/templates
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /policies HTTP/1.1" 200 614
DEBUG:tenable.io.TenableIO:Request-UUID 09 for https://cloud.tenable.com/policies
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /editor/scan/policy/50 HTTP/1.1" 200 10979
DEBUG:tenable.io.TenableIO:Request-UUID 88 for https://cloud.tenable.com/editor/scan/policy/50
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /editor/policy/templates HTTP/1.1" 200 2374
DEBUG:tenable.io.TenableIO:Request-UUID 5b for https://cloud.tenable.com/editor/policy/templates
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /editor/policy/templates HTTP/1.1" 200 2374
DEBUG:tenable.io.TenableIO:Request-UUID 78 for https://cloud.tenable.com/editor/policy/templates
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /editor/scan/templates/ad HTTP/1.1" 200 157768
DEBUG:tenable.io.TenableIO:Request-UUID 71 for https://cloud.tenable.com/editor/scan/templates/ad
DEBUG:tenable.io.TenableIO:path=scans, query={}, body={'settings': {'policy_id': 50, 'scanner_id': '85', 'text_targets': 'hostname', 'folder_id': 115, 'name': 'Test mytioscan'}, 'uuid': 'ab'}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "POST /scans HTTP/1.1" 200 None
DEBUG:tenable.io.TenableIO:Request-UUID 5a for https://cloud.tenable.com/scans
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "POST /scans/245/launch HTTP/1.1" 200 None
DEBUG:tenable.io.TenableIO:Request-UUID 13 for https://cloud.tenable.com/scans/245/launch
```

**Comment by SteveMcGrath** [comment] 2019-11-05 20:08
Aha, the root of the issues is the call to scanners, which is restricted.

**Comment by SteveMcGrath** [comment] 2019-11-05 20:09
What version of pyTenable are you using?

**Comment by maaren** [comment] 2019-11-05 20:39
0.3.26

**Comment by SteveMcGrath** [comment] 2019-11-05 22:47
the issue isn't the library, it's your code.  Your making a call to `tio.scanners.list()` on L27 of your code.  thic calls an API your user doesn't have access to.  If you're trying to resolve the scanner name to a UUID, note that you don't need to, just pass the name.  The library will first check for any name matches before checking against UUIDs.

https://github.com/tenable/pyTenable/blob/2f7476c00333bcc53b2aa9f8eb9fc97e64b017fe/tenable/io/scans.py#L130-L147

**Comment by SteveMcGrath** [comment] 2019-11-05 23:08
To further elaborate on the issue, look at your traceback:

```
Traceback (most recent call last):
  File "./mytioscan", line 119, in <module>
    main()
  File "./mytioscan", line 90, in main
    scanner_uuid = get_scanner_uuid(tio, 'nessus-scanner')
  File "./mytioscan", line 27, in get_scanner_uuid
    for scanner in tio.scanners.list():
  File "/usr/lib/python3.7/site-packages/tenable/io/scanners.py", line 268, in list
    return self._api.get('scanners').json()['scanners']
  File "/usr/lib/python3.7/site-packages/tenable/base.py", line 475, in get
    return self._request('GET', path, **kwargs)
  File "/usr/lib/python3.7/site-packages/tenable/base.py", line 446, in _request
    raise self._error_codes[status](resp)
tenable.errors.PermissionError: 17:403 {"statusCode":403,"error":"Forbidden","message":"Insufficient scope"}
```

If you specifically look here:

```
  File "./mytioscan", line 27, in get_scanner_uuid
    for scanner in tio.scanners.list():
```

you'll see the offending issue ;).  As this isn't a pyTenable issue, I'm closing the ticket.

**Closed by SteveMcGrath** 2019-11-05 23:08 UTC
Labels: as-designed, question

**Comment by atrlogs** [comment] 2019-11-06 06:06
For some reason I thought you had to pass the scanner_uuid. I have changed it now to pass the name of the scanner and that works when I run as Administrator. As Scan Operator I now get:
```
$ ./mytioscan
Using Scan Operator  priviliges
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cloud.tenable.com:443
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /folders HTTP/1.1" 200 None
DEBUG:tenable.io.TenableIO:Request-UUID 47 for https://cloud.tenable.com/folders
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /policies HTTP/1.1" 200 568
DEBUG:tenable.io.TenableIO:Request-UUID 5e for https://cloud.tenable.com/policies
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /editor/policy/templates HTTP/1.1" 403 None
DEBUG:tenable.io.TenableIO:Request-UUID 67 for https://cloud.tenable.com/editor/policy/templates
ERROR:tenable.errors.PermissionError:GET https://cloud.tenable.com/editor/policy/templates >> 67:403 {"error":"You are not authorized to perform this request"}
Traceback (most recent call last):
  File "./mytioscan", line 118, in <module>
    main()
  File "./mytioscan", line 99, in main
    scan = tio.scans.create(**params)
  File "/usr/lib/python3.7/site-packages/tenable/io/scans.py", line 369, in create
    scan = self._create_scan_document(kw)
  File "/usr/lib/python3.7/site-packages/tenable/io/scans.py", line 99, in _create_scan_document
    templates = self._api.policies.templates()
  File "/usr/lib/python3.7/site-packages/tenable/io/policies.py", line 35, in templates
    for item in self._api.editor.template_list('policy'):
  File "/usr/lib/python3.7/site-packages/tenable/io/editor.py", line 236, in template_list
    self._check('etype', etype, str, choices=['scan', 'policy'])
  File "/usr/lib/python3.7/site-packages/tenable/base.py", line 511, in get
    return self._request('GET', path, **kwargs)
  File "/usr/lib/python3.7/site-packages/tenable/base.py", line 482, in _request
    raise self._error_codes[status](resp)
tenable.errors.PermissionError: 67:403 {"error":"You are not authorized to perform this request"}
```

What I am trying to do is to allow a devops pipeline to perform a compliance scan of a linux box that they have created. Using the webgui they can do it as Scan Operator, but using the API we are struggling...

**Comment by nkeuning** [comment] 2019-11-06 06:24
Please open a support case with our standard support team. This seems to be a platform mismatch in what permissions are applied.  The UI regularly uses private apis that may have different permission available/applied to a specific group.  I'd recommend including all the detail here, to help direct this to the correct team.
